In [1]:
import numpy as np

Trabajaremos con el archivo posicion_velocidad_coment.dat que se muestra aquí:


```#posicion velocidad
0.0  30
0.8  50
1.5  43.2
2.0  20.0
2.6  42.1```

In [2]:
str_archivo = 'Data/Clases/posicion_velocidad_coment.dat'

# Función loadtxt

Usamos la función loadtxt de numpy que nos permite procesar archivos con datos númericos

In [3]:
np.loadtxt?

Existen las opciones de definir el tipo de información a procesar como float, string, double etc, el delimitador de los valores y el saltar los primeras n lineas con skiprows.

In [4]:
np.loadtxt(str_archivo)

array([[  0. ,  30. ],
       [  0.8,  50. ],
       [  1.5,  43.2],
       [  2. ,  20. ],
       [  2.6,  42.1]])

In [5]:
data = np.loadtxt(str_archivo)

In [6]:
data[:,0]

array([ 0. ,  0.8,  1.5,  2. ,  2.6])

In [7]:
data[:,1]

array([ 30. ,  50. ,  43.2,  20. ,  42.1])

In [8]:
x = data[:,0]

In [9]:
v = data[:,1]

In [10]:
x, v

(array([ 0. ,  0.8,  1.5,  2. ,  2.6]),
 array([ 30. ,  50. ,  43.2,  20. ,  42.1]))

Ahora importamos directamente en las dos variables con opción "unpack"

In [11]:
x,v  = np.loadtxt(str_archivo,unpack=True)

In [12]:
x

array([ 0. ,  0.8,  1.5,  2. ,  2.6])

# Función genfromtxt

Usamos la alternativa de genfromtxt para trabajar con archivos que incompletos de datos y para tener mayor flexibilidad en el procesamiento.


In [13]:
np.genfromtxt?

El archivo posicion_velocidad_missing.dat le falta un valor en la velocidad:

```@ Archivo obtenido el 30 diciembre 2016
0.0  30
0.8  50
1.5  43.2
2.0  Bla 
2.6  42.1```

In [14]:
str_archivo = 'Data/Clases/posicion_velocidad_missing.dat'
data = np.genfromtxt(str_archivo,comments='@')

In [15]:
data

array([[  0. ,  30. ],
       [  0.8,  50. ],
       [  1.5,  43.2],
       [  2. ,   nan],
       [  2.6,  42.1]])

Como cambiamos el valor del item ausente?

In [16]:
data = np.genfromtxt(str_archivo,comments='@',filling_values='0.0')

In [17]:
data

array([[  0. ,  30. ],
       [  0.8,  50. ],
       [  1.5,  43.2],
       [  2. ,   0. ],
       [  2.6,  42.1]])

Cómo podemos procesar la nombre de la variable de los valores que se esta leyendo. 

Como ejemplo se usará el archivo posicion_velocidad_names.dat:

```@ Archivo obtenido el 30 diciembre 2016
x    v
0.0  30
0.8  50
1.5  43.2
2.0  Bla 
2.6  42.1```

In [18]:
str_archivo = 'Data/Clases/posicion_velocidad_names.dat'
data1 = np.genfromtxt(str_archivo,skip_header=1,names=True,filling_values='0.0')

In [19]:
data1

array([(0.0, 30.0), (0.8, 50.0), (1.5, 43.2), (2.0, 0.0), (2.6, 42.1)], 
      dtype=[('x', '<f8'), ('v', '<f8')])

In [21]:
type(data1)

numpy.ndarray

In [22]:
data1['v']

array([ 30. ,  50. ,  43.2,   0. ,  42.1])

In [23]:
data1['x']

array([ 0. ,  0.8,  1.5,  2. ,  2.6])

In [24]:
np.genfromtxt?